version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/ruby?version=1.4.0
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.1.1'
    steps:
      - checkout
      - ruby/install-deps:
        bundler-version: 2.3.3

  test:
    docker:
      - image: 'cimg/ruby:3.1.1'
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps:
        bundler-version: 2.3.3
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
